language: node_js
node_js:
  - '12'
  - '14'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - sox
      - gnuplot
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.9
env:
  - CXX=g++-4.9
